# -*- coding: utf-8 -*-
"""
Agrega campo "intro" a las 46 entradas de "Prescripcion de deuda TAG"
en data/paginas.json. No toca ninguna otra entrada.
"""
import json, os

BASE = os.path.dirname(os.path.abspath(__file__))
PATH = os.path.join(BASE, "data", "paginas.json")

INTROS = {
    "prescripcion-deuda-tag-santiago": "El Juzgado Civil de Santiago, ubicado en Huérfanos 1409, Santiago Centro, recibe solicitudes de prescripción de deuda TAG de lunes a viernes de 8:30 a 14:00. Santiago concentra la mayor cantidad de causas TAG del país dada su extensa red de autopistas urbanas: Costanera Norte, Autopista Central, Vespucio Sur y Norte Express. Si tu multa TAG supera los 3 años sin cobro judicial, la prescripción puede extinguir la deuda por completo.",
    "prescripcion-deuda-tag-providencia": "Los vecinos de Providencia que tengan deudas TAG con más de 3 años de antigüedad deben presentar la solicitud de prescripción ante el Juzgado Civil de Santiago, en Huérfanos 1409. Providencia está cruzada por Costanera Norte y Vespucio, dos autopistas con alta frecuencia de cobros TAG. El plazo legal de prescripción es de 3 años contados desde la fecha del cobro, según el Art. 2515 del Código Civil.",
    "prescripcion-deuda-tag-las-condes": "Las Condes, atravesada por las autopistas Costanera Norte y Américo Vespucio, genera una alta cantidad de cobros TAG. Si tu deuda tiene más de 3 años sin notificación judicial, puedes alegarla como prescrita ante el Juzgado Civil de Santiago (Huérfanos 1409). El tribunal atiende de lunes a viernes y no se requiere abogado para presentar la solicitud inicial en causas de menor cuantía.",
    "prescripcion-deuda-tag-maipu": "Maipú, una de las comunas más grandes de Chile, está conectada a Autopista del Sol y Vespucio Sur, lo que genera un volumen significativo de deudas TAG. El Juzgado Civil de Maipú, en Av. 5 de Abril 1825, es el tribunal competente para alegar prescripción de estas deudas. Si la multa tiene más de 3 años sin gestión judicial de la concesionaria, la prescripción extingue la obligación.",
    "prescripcion-deuda-tag-pudahuel": "Pudahuel está cruzada por la Autopista del Sol y Ruta 68, ambas con sistemas de cobro TAG activos. El Juzgado Civil de Pudahuel, en Av. Pudahuel 9260, conoce las causas de prescripción de deuda TAG de la comuna. La acción ejecutiva prescribe a los 3 años desde la fecha del cobro: si ese plazo pasó sin demanda judicial, puedes solicitar la declaración de prescripción.",
    "prescripcion-deuda-tag-la-florida": "La Florida es una de las comunas con mayor tránsito por Vespucio Sur. Las deudas TAG de sus vecinos se presentan ante el Juzgado Civil de San Miguel, ubicado en Av. Departamental 4132. La prescripción de 3 años aplica a cobros ejecutivos de autopistas de concesión. Generado el escrito de prescripción con LegalHelp, puedes presentarlo directamente en el tribunal sin necesidad de abogado para la etapa inicial.",
    "prescripcion-deuda-tag-puente-alto": "Puente Alto tiene jurisdicción propia: el Juzgado Civil de Puente Alto, ubicado en Manuel Rodríguez 280, atiende las causas de prescripción de deuda TAG de sus vecinos. La comuna está conectada a Autopista Central y Vespucio, con alta densidad de cobros. Si tu deuda TAG supera los 3 años sin notificación judicial, el plazo de prescripción ejecutiva habrá operado de pleno derecho.",
    "prescripcion-deuda-tag-concepcion": "Concepción cuenta con el Juzgado Civil en O'Higgins 660, Palacio de Justicia, tribunal competente para causas de prescripción TAG de la región del Biobío. Las autopistas y rutas concesionadas del Gran Concepción generan cobros TAG que prescriben a los 3 años según el Art. 2515 CC. La solicitud de prescripción debe presentarse en formato escrito ante este tribunal.",
    "prescripcion-deuda-tag-valparaiso": "El Juzgado Civil de Valparaíso, ubicado en Av. Brasil 2960, Palacio de Justicia, tramita las causas de prescripción de deuda TAG de la región de Valparaíso. Las rutas de acceso a la ciudad y la Autopista del Litoral generan cobros que pueden prescribir si han pasado más de 3 años sin acción judicial de la concesionaria. Presenta tu solicitud antes de que el acreedor la demande.",
    "prescripcion-deuda-tag-san-bernardo": "San Bernardo tiene tribunal propio: el Juzgado Civil de San Bernardo, Freire 210, atiende causas de deuda TAG de sus vecinos. La Autopista del Sol pasa por la comuna, generando cobros frecuentes. Si la deuda tiene más de 3 años sin demanda judicial, la prescripción extintiva permite alegarla en este tribunal y obtener la extinción de la obligación.",
    "prescripcion-deuda-tag-penalolen": "Peñalolén está conectada a Vespucio Norte y Américo Vespucio Sur, autopistas con alto tráfico de cobros TAG. Las causas de prescripción de deuda TAG de Peñalolén corresponden al Juzgado Civil de Santiago, Huérfanos 1409. Si no hubo gestión judicial del cobro en los últimos 3 años, la acción ejecutiva de las concesionarias ya prescribió.",
    "prescripcion-deuda-tag-el-bosque": "El Bosque está vinculado al Juzgado Civil de San Miguel, Av. Pedro Aguirre Cerda 5960, para efectos de causas civiles como la prescripción de deuda TAG. Las autopistas que cruzan el sector sur de Santiago generan cobros TAG que pueden prescribir. La solicitud se presenta directamente en el tribunal, con o sin abogado según la cuantía de la deuda.",
    "prescripcion-deuda-tag-quilicura": "Quilicura tiene tribunal civil propio: Juzgado de Letras en lo Civil de Quilicura, Av. Matta 1285. La Autopista del Sol y Ruta 5 Norte pasan por la comuna. Si la concesionaria no ha notificado el cobro judicialmente en los últimos 3 años, el plazo de prescripción ejecutiva se habrá cumplido y puedes solicitar la extinción de la deuda TAG.",
    "prescripcion-deuda-tag-nunoa": "Ñuñoa está conectada a Vespucio y Av. Grecia, con peajes y cobros TAG asociados a autopistas urbanas del sector oriente. Las causas de prescripción de sus vecinos se tramitan ante el Juzgado Civil de Santiago, Huérfanos 1409. Si la deuda TAG tiene más de 3 años de antigüedad sin cobro judicial, puedes alegarla como prescrita sin costo de abogado en la etapa inicial.",
    "prescripcion-deuda-tag-recoleta": "Recoleta es una comuna del norte de Santiago conectada a Vespucio Norte y Autopista Nororiente. Las deudas TAG de sus vecinos se tramitan ante el Juzgado Civil de Santiago, Huérfanos 1409. La acción ejecutiva prescribe a los 3 años desde la fecha del cobro (Art. 2515 CC): pasado ese plazo, la concesionaria no puede cobrar judicialmente.",
    "prescripcion-deuda-tag-estacion-central": "Estación Central está conectada a Autopista Central y Acceso Sur, con alta actividad de cobros TAG. Sus causas de prescripción se tramitan en el Juzgado Civil de Santiago, Huérfanos 1409. Si tienes deudas TAG con más de 3 años sin notificación judicial, el escrito de excepción de prescripción es el documento clave para presentar ante el tribunal.",
    "prescripcion-deuda-tag-vitacura": "Vitacura está conectada a Costanera Norte y Kennedy, con peajes y TAG activos. Las causas de prescripción de deuda TAG de Vitacura se tramitan ante el Juzgado Civil de Santiago, Huérfanos 1409. El Art. 2515 del Código Civil establece que la acción ejecutiva prescribe a los 3 años: si ese plazo pasó, puedes solicitar la extinción de la deuda.",
    "prescripcion-deuda-tag-lo-barnechea": "Lo Barnechea está en el sector oriente de Santiago, conectada a Costanera Norte y túneles de acceso con TAG. Las deudas TAG de sus vecinos corresponden al Juzgado Civil de Santiago, Huérfanos 1409. Si la deuda tiene más de 3 años sin demanda judicial de la concesionaria, el plazo de prescripción ejecutiva se cumplió y puedes alegarla formalmente.",
    "prescripcion-deuda-tag-colina": "Colina está recorrida por Ruta 5 Norte y vías de acceso con peaje. El Juzgado Civil de Colina, Av. Colina 1100, es el tribunal competente para las causas de prescripción de deuda TAG de la comuna. Pasados 3 años desde el cobro sin acción judicial, la concesionaria pierde el derecho a ejecutar judicialmente la deuda.",
    "prescripcion-deuda-tag-lampa": "Lampa está conectada a Ruta 5 Norte y Autopista del Sol, con cobros TAG en sus accesos. Las causas de prescripción de sus vecinos se tramitan en el Juzgado Civil de Colina, Av. Colina 1100, tribunal competente para el sector. Si la deuda tiene más de 3 años sin cobro judicial, la acción ejecutiva está prescrita y puedes solicitarlo formalmente.",
    "prescripcion-deuda-tag-independencia": "Independencia es una comuna del norte de Santiago conectada a la Autopista Nororiente y Vespucio Norte. Sus deudas TAG prescriben a los 3 años (Art. 2515 CC) y se tramitan ante el Juzgado Civil de Santiago, Huérfanos 1409. Si no recibiste notificación judicial en ese plazo, puedes presentar la excepción de prescripción con el documento generado por LegalHelp.",
    "prescripcion-deuda-tag-san-miguel": "San Miguel tiene tribunal propio: Juzgado Civil de San Miguel, Av. Pedro Aguirre Cerda 5960, competente para causas TAG del sector sur de Santiago. La Autopista Central y Vespucio Sur generan cobros frecuentes en esta zona. Si la deuda tiene más de 3 años sin demanda judicial, la prescripción extintiva es tu defensa legal principal.",
    "prescripcion-deuda-tag-cerro-navia": "Cerro Navia está en el sector poniente de Santiago, zona de alta presencia de Autopista del Sol. Las causas de prescripción de deuda TAG se tramitan en el Juzgado Civil de Pudahuel, Av. Pudahuel 9260. Pasado el plazo de 3 años sin cobro judicial, puedes presentar el escrito de excepción de prescripción directamente en ese tribunal.",
    "prescripcion-deuda-tag-renca": "Renca está vinculada a Autopista del Sol y accesos del sector poniente de Santiago. Sus causas de prescripción TAG se tramitan en el Juzgado Civil de Santiago, Huérfanos 1409. Si la deuda tiene más de 3 años sin notificación judicial, el Art. 2515 CC permite alegar la prescripción extintiva de la acción ejecutiva y solicitar su extinción formal.",
    "prescripcion-deuda-tag-quinta-normal": "Quinta Normal está conectada a Autopista Central y accesos poniente. Sus vecinos tramitan prescripciones de deuda TAG en el Juzgado Civil de Santiago, Huérfanos 1409. La prescripción de 3 años corre desde la fecha en que la concesionaria generó el cobro. Pasado ese plazo sin demanda, puedes solicitar formalmente la extinción de la deuda.",
    "prescripcion-deuda-tag-vina-del-mar": "Viña del Mar tiene tribunal propio: el Juzgado Civil de Viña del Mar, Av. Arlegui 555, atiende causas de prescripción de deuda TAG de la región de Valparaíso. La Autopista del Litoral y Ruta 68 generan cobros TAG en accesos a Viña. Si la deuda supera los 3 años sin cobro judicial, puedes solicitar la prescripción ante este tribunal.",
    "prescripcion-deuda-tag-quilpue": "Quilpué está en la región de Valparaíso y cuenta con el Juzgado Civil de Quilpué, Av. O'Higgins 540, para causas de prescripción de deuda TAG. Las deudas vinculadas a la Ruta 68 y accesos concesionados de la región prescriben a los 3 años. Presenta la solicitud de prescripción antes de que la concesionaria inicie acción judicial.",
    "prescripcion-deuda-tag-san-antonio": "San Antonio tiene tribunal propio: Juzgado Civil de San Antonio, Av. Centenario 290. La ruta de acceso al puerto y Autopista del Sol generan cobros TAG que prescriben a los 3 años (Art. 2515 CC). Si no recibiste demanda judicial en ese plazo, puedes presentar la excepción de prescripción ante este tribunal y solicitar la extinción de la deuda.",
    "prescripcion-deuda-tag-talcahuano": "Talcahuano está en el Gran Concepción, conectada a rutas concesionadas del Biobío. El Juzgado Civil de Talcahuano, Colón 601, es el tribunal competente para las causas de prescripción TAG de la comuna. Si la deuda supera los 3 años sin cobro judicial, el plazo del Art. 2515 CC se cumplió y puedes alegar la prescripción.",
    "prescripcion-deuda-tag-los-angeles": "Los Ángeles es la capital de la provincia de Biobío, con conexión a Ruta 5 Sur y accesos concesionados. El Juzgado Civil de Los Ángeles, Ercilla 368, tramita las causas de prescripción de deuda TAG. Pasados 3 años desde el cobro sin demanda judicial de la concesionaria, la deuda TAG puede declararse prescrita.",
    "prescripcion-deuda-tag-chillan": "Chillán está conectada a Ruta 5 Sur y vías concesionadas de la región de Ñuble. El Juzgado Civil de Chillán, Constitución 550, es competente para causas de prescripción de deuda TAG. La acción ejecutiva prescribe en 3 años: si ese plazo pasó sin notificación judicial, puedes presentar la solicitud de prescripción ante este tribunal.",
    "prescripcion-deuda-tag-temuco": "Temuco es la capital de La Araucanía, conectada a Ruta 5 Sur y accesos concesionados. El Juzgado Civil de Temuco, Manuel Montt 660, tramita las causas de prescripción de deuda TAG de la región. Si la deuda tiene más de 3 años sin cobro judicial, el plazo de prescripción ejecutiva se cumplió y puedes solicitar su extinción formal.",
    "prescripcion-deuda-tag-padre-las-casas": "Padre Las Casas, colindante con Temuco, está conectada a Ruta 5 Sur con cobros TAG en sus accesos. Las causas de prescripción de sus vecinos se tramitan en el Juzgado Civil de Temuco, Manuel Montt 660. Si la deuda TAG tiene más de 3 años sin acción judicial de la concesionaria, puedes alegarla como prescrita ante ese tribunal.",
    "prescripcion-deuda-tag-puerto-montt": "Puerto Montt es la capital de la región de Los Lagos, con conexión a Ruta 5 Sur. El Juzgado Civil de Puerto Montt, Av. O'Higgins 222, tramita causas de prescripción de deuda TAG. La acción ejecutiva prescribe a los 3 años (Art. 2515 CC): pasado ese plazo sin demanda judicial, puedes solicitar la extinción de la deuda ante este tribunal.",
    "prescripcion-deuda-tag-osorno": "Osorno está en la región de Los Lagos, conectada a Ruta 5 Sur. El Juzgado Civil de Osorno, Manuel Rodríguez 855, tramita las causas de prescripción de deuda TAG de la provincia. Si la concesionaria no inició acción judicial en los últimos 3 años, la prescripción extintiva opera y puedes solicitar la extinción formal de la deuda.",
    "prescripcion-deuda-tag-la-serena": "La Serena es la capital de la región de Coquimbo, con conexión a Ruta 5 Norte y accesos concesionados. El Juzgado Civil de La Serena, Balmaceda 986, tramita causas de prescripción de deuda TAG. Pasados 3 años desde el cobro sin notificación judicial, la deuda puede declararse prescrita mediante solicitud formal ante este tribunal.",
    "prescripcion-deuda-tag-coquimbo": "Coquimbo está conectada a Ruta 5 Norte con peajes activos. El Juzgado Civil de Coquimbo, Av. Costanera 1000, tramita las causas de prescripción de deuda TAG de la región. Si la deuda supera los 3 años sin cobro judicial, puedes presentar la solicitud de prescripción ante este tribunal y solicitar la extinción formal de la obligación.",
    "prescripcion-deuda-tag-antofagasta": "Antofagasta está conectada a Ruta 5 Norte y accesos mineros concesionados. El Juzgado Civil de Antofagasta, Av. Prat 256, tramita causas de prescripción de deuda TAG de la región. La acción ejecutiva prescribe a los 3 años desde el cobro: si ese plazo pasó sin demanda judicial, puedes solicitar la declaración de prescripción ante este tribunal.",
    "prescripcion-deuda-tag-iquique": "Iquique está conectada a Ruta 5 Norte y accesos de la región de Tarapacá. El Juzgado Civil de Iquique, Vivar 491, es el tribunal competente para causas de prescripción de deuda TAG. Si la concesionaria no inició acción judicial en los últimos 3 años, el plazo del Art. 2515 CC se cumplió y puedes solicitar la extinción formal de la deuda.",
    "prescripcion-deuda-tag-arica": "Arica está en el extremo norte de Chile, conectada a Ruta 5 Norte. El Juzgado Civil de Arica, Sotomayor 415, tramita causas de prescripción de deuda TAG de la región de Arica y Parinacota. Pasados 3 años desde el cobro sin acción judicial de la concesionaria, puedes presentar la solicitud de prescripción ante este tribunal.",
    "prescripcion-deuda-tag-rancagua": "Rancagua es la capital de la región de O'Higgins, conectada a Autopista del Libertadores y Ruta 5 Sur. El Juzgado Civil de Rancagua, Av. Brasil 685, tramita causas de prescripción de deuda TAG. Si la deuda tiene más de 3 años sin cobro judicial, el plazo prescriptivo del Art. 2515 CC se cumplió y puedes alegar la prescripción formalmente.",
    "prescripcion-deuda-tag-talca": "Talca es la capital de la región del Maule, conectada a Ruta 5 Sur con peajes activos. El Juzgado Civil de Talca, 2 Norte 1259, tramita las causas de prescripción de deuda TAG. Si la concesionaria no demandó judicialmente en los últimos 3 años desde el cobro, la acción ejecutiva prescribió y puedes solicitar la extinción formal de la deuda.",
    "prescripcion-deuda-tag-curico": "Curicó está en la región del Maule, conectada a Ruta 5 Sur. El Juzgado Civil de Curicó, Prat 427, tramita las causas de prescripción de deuda TAG. La acción ejecutiva prescribe en 3 años desde el cobro (Art. 2515 CC). Si ese plazo pasó sin notificación judicial, puedes solicitar la declaración de prescripción ante este tribunal.",
    "prescripcion-deuda-tag-copiapo": "Copiapó es la capital de la región de Atacama, conectada a Ruta 5 Norte. El Juzgado Civil de Copiapó, Los Carrera 201, tramita causas de prescripción de deuda TAG. Si la deuda supera los 3 años sin demanda judicial de la concesionaria, puedes presentar la solicitud de prescripción ante este tribunal y lograr la extinción de la obligación.",
    "prescripcion-deuda-tag-punta-arenas": "Punta Arenas es la capital de la región de Magallanes. El Juzgado Civil de Punta Arenas, Av. Errázuriz 928, tramita causas civiles de la región, incluyendo prescripción de deudas TAG vinculadas a rutas y accesos concesionados. Pasados 3 años desde el cobro sin notificación judicial, puedes solicitar la extinción formal de la deuda ante este tribunal.",
}

with open(PATH, encoding="utf-8") as f:
    data = json.load(f)

updated = 0
for entry in data:
    slug = entry.get("slug", "")
    if slug in INTROS and "intro" not in entry:
        entry["intro"] = INTROS[slug]
        updated += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"OK: {updated} entradas actualizadas con campo 'intro'")
